---
ansible_python_interpreter: /usr/bin/python3 # noqa: var-naming[no-role-prefix]
bash_executables: /usr/bin/bash # noqa: var-naming[no-role-prefix]

dotfiles_dist_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - ipcalc
  - jq
  - nmap
  - tcpdump
  - tmux
  - vim
  - wget
  - wireshark
  - zsh
  - duf
  - exa
