---
ansible_python_interpreter: /usr/bin/python3

setup_dist_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - ipcalc
  - jq
  - nmap
  - tcpdump
  - tmux
  - vim
  - wget
  - wireshark
  - zsh
