---
- name: Ensure Zsh is the user's shell
  ansible.builtin.user:
    name: "{{ setup_system_username }}"
    shell: /usr/bin/zsh

- name: Download and install oh-my-zsh
  become_user: "{{ setup_system_username }}"
  ansible.builtin.shell: |
    set -o pipefail && \
      curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | \
      bash -
    args:
      chdir: "{{ setup_system_user_home }}"
      creates: .install/oh-my-zsh.sh
      executable: /usr/bin/bash
