---
- name: Copy gtk.css
  ansible.builtin.copy:
    src: gtk-3.0/gtk.css
    dest: "{{ dotfiles_system_user_home }}/.config/gtk-3.0/gtk.css"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"

- name: Import gnome-terminal settings
  block:
    - name: Generate gnome-terminal settings file
      ansible.builtin.template:
        src: gnome-terminal-settings.j2
        dest: "{{ dotfiles_system_user_template_dir }}/gnome-terminal-settings"
        owner: "{{ dotfiles_system_username }}"
        group: "{{ dotfiles_system_user_group }}"
        mode: "0644"
      register: __gnome_terminal_settings
    - name: Load setting using dconf load
      become: true
      become_user: "{{ dotfiles_system_username }}"
      ansible.builtin.shell: >
        dconf load /org/gnome/terminal/legacy/ < {{ dotfiles_system_user_template_dir }}/gnome-terminal-settings
      changed_when: true
      when: # noqa: no-handler
        - __gnome_terminal_settings is changed
  rescue:
    - name: Delete gnome-terminal settings file
      ansible.builtin.file:
        path: "{{ dotfiles_system_user_template_dir }}/gnome-terminal-settings"
        state: absent
