---
- name: Ensure all directories exists
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - .cht.sh
  loop_control:
    loop_var: __item

- name: Generate .cht.sh.conf file
  ansible.builtin.template:
    src: cht-sh-conf.j2
    dest: "{{ dotfiles_system_user_home }}/.cht.sh/cht.sh.conf"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"

- name: Download and install cheat.sh
  ansible.builtin.get_url:
    url: https://cht.sh/:cht.sh
    dest: "{{ dotfiles_system_user_home }}/.local/bin/cht.sh"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
  register: __install_cheat_sh
  until: __install_cheat_sh is succeeded
  retries: 10
  delay: 5
