---
- name: Generate .gitconfig file
  ansible.builtin.template:
    src: git-config.j2
    dest: "{{ dotfiles_system_user_home }}/.gitconfig"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_username }}"
    mode: "0644"
