---
- name: Ensure all directories exists
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - .testssl.sh
  loop_control:
    loop_var: __item

- name: Download and install testssl.sh
  ansible.builtin.unarchive:
    src: https://github.com/testssl/testssl.sh/archive/refs/tags/v{{ dotfiles_testssl_sh_version }}.tar.gz
    dest: "{{ dotfiles_system_user_home }}/.testssl.sh"
    mode: "0755"
    remote_src: true
  register: __install_testssl_sh
  until: __install_testssl_sh is succeeded
  retries: 5
  delay: 2

- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ dotfiles_system_user_home }}/.testssl.sh/testssl.sh-{{ dotfiles_testssl_sh_version }}/testssl.sh"
    dest: /usr/local/bin/testssl.sh
    state: link
