---
- name: Create tmux dir
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/.tmux"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory

- name: Generate .tmux.conf file
  ansible.builtin.template:
    src: tmux-config.j2
    dest: "{{ dotfiles_system_user_home }}/.tmux.conf"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"
