---
- name: Create pathogen dirs
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/.vim/{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - autoload
    - bundle
  loop_control:
    loop_var: __item

- name: Download and install pathogen
  ansible.builtin.get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ dotfiles_system_user_home }}/.vim/autoload/pathogen.vim"
    mode: "0755"

- name: Download and install NERDTree plugin
  ansible.builtin.git:
    repo: https://github.com/scrooloose/nerdtree.git
    dest: "{{ dotfiles_system_user_home }}/.vim/bundle/nerdtree"
    version: "{{ dotfiles_vim_nerdtree_version }}"

- name: Generate .vimrc file
  ansible.builtin.template:
    src: vim-config.j2
    dest: "{{ dotfiles_system_user_home }}/.vimrc"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"
