---
- name: Ensure all directories exists
  ansible.builtin.file:
    path: "{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ dotfiles_yc_disk_config_dir }}"
    - "{{ dotfiles_yc_disk_dir }}"
  loop_control:
    loop_var: __item

- name: Generate Yandex.Disk config
  ansible.builtin.template:
    src: yandex-disk-config.j2
    dest: "{{ dotfiles_yc_disk_config_dir }}/config.cfg"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"

- name: Generate systemd unit file
  ansible.builtin.template:
    src: yandex-disk.service.j2
    dest: /etc/systemd/system/yandex-disk.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload daemon
    - Restart yandex-disk
  when:
    - dotfiles_yc_disk_systemd_enabled | bool

- name: Add an apt signing key for Yandex.Disk
  ansible.builtin.apt_key:
    url: http://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG
    keyring: /etc/apt/keyrings/yandex-disk.gpg
    state: present

- name: Adding apt repository for Yandex.Disk
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/yandex-disk.gpg] http://repo.yandex.ru/yandex-disk/deb/ stable main
    state: present
    filename: yandex-disk

- name: Install yandex-disk binary
  ansible.builtin.apt:
    name: yandex-disk
    update_cache: true
