---
- name: Create source files
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"
    state: touch
    access_time: preserve
    modification_time: preserve
  loop: "{{ dotfiles_zshrc_source_files }}"
  loop_control:
    loop_var: __item

- name: Ensure Zsh is the user's shell
  ansible.builtin.user:
    name: "{{ dotfiles_system_username }}"
    shell: /usr/bin/zsh

- name: Check ~/.oh-my-zsh dir
  ansible.builtin.stat:
    path: "{{ dotfiles_system_user_home }}/.oh-my-zsh"
  register: __oh_my_zsh_dir

- name: Absent ~/.oh-my-zsh dir
  ansible.builtin.file:
    path: "{{ dotfiles_system_user_home }}/.oh-my-zsh"
    state: absent
  when:
    - __oh_my_zsh_dir.stat.exists
    - dotfiles_zsh_oh_my_zsh_reinstall

- name: Download and install oh-my-zsh
  become: true
  become_user: "{{ dotfiles_system_username }}"
  ansible.builtin.shell: |
    set -o pipefail && \
      curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | \
      bash -
  args:
    chdir: "{{ dotfiles_system_user_home }}"
    executable: /usr/bin/bash
  changed_when: true
  when:
    - not __oh_my_zsh_dir.stat.exists or dotfiles_zsh_oh_my_zsh_reinstall

- name: Install gnzh.no-ruby-prompt.zsh-theme
  ansible.builtin.copy:
    src: files/zsh/themes/gnzh.no-ruby-prompt.zsh-theme
    dest: "{{ dotfiles_system_user_home }}/.oh-my-zsh/themes/gnzh.no-ruby-prompt.zsh-theme"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"

- name: Generate .zshrc file
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ dotfiles_system_user_home }}/.zshrc"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"

- name: Generate .shell_funcs file
  ansible.builtin.template:
    src: shell-funcs.j2
    dest: "{{ dotfiles_system_user_home }}/.shell_funcs"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0644"
