---
- name: Ensure all packages is installed
  ansible.builtin.package:
    name: "{{ __item }}"
    state: present
    update_cache: true
  loop:
    - "{{ setup_dist_packages }}"
  loop_control:
    loop_var: __item
