---
- name: Include OS specific variables
  ansible.builtin.include_tasks: vars.yaml

- name: Ensure /etc/apt/keyrings dir is present
  ansible.builtin.file:
    name: /etc/apt/keyrings
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create required dirs
  ansible.builtin.file:
    path: "{{ __item }}"
    owner: "{{ dotfiles_system_username }}"
    group: "{{ dotfiles_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ dotfiles_system_user_template_dir }}"
    - "{{ dotfiles_system_user_home }}/.config"
  loop_control:
    loop_var: __item

- name: Install dist packages
  ansible.builtin.include_tasks: pkg.yaml

- name: Install and setup tools
  ansible.builtin.include_tasks: tools.yaml
