---
- name: Include OS specific variables
  ansible.builtin.include_tasks: vars.yaml

- name: Create required dirs
  ansible.builtin.file:
    path: "{{ __item }}"
    owner: "{{ setup_system_username }}"
    group: "{{ setup_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ setup_system_user_template_dir }}"
    - "{{ setup_system_user_home }}/.config"
  loop_control:
    loop_var: __item

- name: Install dist packages
  ansible.builtin.include_tasks: install.yaml

- name: Setup Git
  ansible.builtin.include_tasks: setup-git.yaml

- name: Setup zsh
  ansible.builtin.include_tasks: setup-zsh.yaml

- name: Setup Vim
  ansible.builtin.include_tasks: setup-vim.yaml

- name: Setup Tmux
  ansible.builtin.include_tasks: setup-tmux.yaml

- name: Setup terminal
  ansible.builtin.include_tasks: setup-terminal.yaml

- name: Setup python
  ansible.builtin.include_tasks: setup-python.yaml
