---
- name: Include OS specific variables
  ansible.builtin.include_tasks: vars.yaml

- name: Create required dirs
  ansible.builtin.file:
    path: "{{ __item }}"
    owner: "{{ setup_system_username }}"
    group: "{{ setup_system_user_group }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ setup_system_user_template_dir }}"
    - "{{ setup_system_user_home }}/.config"
  loop_control:
    loop_var: __item

- name: Install dist packages
  ansible.builtin.include_tasks: pkg.yaml

- name: Install and setup tools
  ansible.builtin.include_tasks: tools.yaml
