---
- name: Include variables for Ubuntu 20.04
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
  ansible.builtin.include_vars: Ubuntu-20.04.yaml

- name: Include variables for Ubuntu 22.04
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
  ansible.builtin.include_vars: Ubuntu-22.04.yaml
