---
- name: Include variables for Ubuntu 20.04
  ansible.builtin.include_vars: Ubuntu-20.04.yaml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"

- name: Include variables for Ubuntu 22.04
  ansible.builtin.include_vars: Ubuntu-22.04.yaml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "22.04"

- name: Include variables for Ubuntu 26.04
  ansible.builtin.include_vars: Ubuntu-26.04.yaml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "26.04"
