---
dotfiles_system_username: foobar
dotfiles_system_user_group: "{{ dotfiles_system_username }}"
dotfiles_system_user_home: /home/{{ dotfiles_system_username }}
dotfiles_system_user_template_dir: "{{ dotfiles_system_user_home }}/.templates"

dotfiles_git_username: foobar
dotfiles_git_user_email: foo@bar.baz

dotfiles_zsh_theme: gnzh.no-ruby-prompt
dotfiles_zsh_oh_my_zsh_reinstall: false
dotfiles_zshrc_source_files:
  - .shell_aliases
  - .shell_autocomp
  - .shell_envs
  - .shell_funcs
  - .work_dirs

dotfiles_vim_nerdtree_version: bc606c4

dotfiles_gnome_terminal_font_name: Monospace
dotfiles_gnome_terminal_font_size: 12
dotfiles_gnome_terminal_font: "{{ dotfiles_gnome_terminal_font_name }} {{ dotfiles_gnome_terminal_font_size }}"
dotfiles_gnome_terminal_default_size_columns: 120
dotfiles_gnome_terminal_default_size_rows: 48

dotfiles_k8s_kubectl_version: 1.29.1
dotfiles_k8s_k9s_version: 0.32.3
dotfiles_k8s_k9s_ui_skin: solarized-light
dotfiles_k8s_k9s_shell_pod_image: busybox:1.36.1
dotfiles_k8s_k9s_shell_pod_namespace: default
dotfiles_k8s_krew_version: 0.4.4
dotfiles_k8s_krew_plugins:
  - krew
  - deprecations
  - outdated

dotfiles_yc_disk_dir: "{{ dotfiles_system_user_home }}/my-disk"
dotfiles_yc_disk_config_dir: "{{ dotfiles_system_user_home }}/.config/yandex-disk"
dotfiles_yc_disk_exclude_dirs: ""
dotfiles_yc_disk_systemd_enabled: false
