---
setup_system_username: foobar
setup_system_user_group: "{{ setup_system_username }}"
setup_system_user_home: /home/{{ setup_system_username }}
setup_system_user_template_dir: "{{ setup_system_user_home }}/.templates"

setup_git_username: foobar
setup_git_user_email: foo@bar.baz

setup_zsh_theme: gnzh.no-ruby-prompt
setup_zsh_oh_my_zsh_reinstall: false
setup_zshrc_source_files:
  - .shell_aliases
  - .shell_autocomp
  - .shell_envs
  - .shell_funcs
  - .work_dirs

setup_vim_nerdtree_version: bc606c4

setup_gnome_terminal_font_name: Monospace
setup_gnome_terminal_font_size: 12
setup_gnome_terminal_font: "{{ setup_gnome_terminal_font_name }} {{ setup_gnome_terminal_font_size }}"
setup_gnome_terminal_default_size_columns: 120
setup_gnome_terminal_default_size_rows: 48

setup_k8s_kubectl_version: 1.29.1
setup_k8s_k9s_version: 0.32.3
setup_k8s_k9s_ui_skin: solarized-light
setup_k8s_k9s_shell_pod_image: busybox:1.36.1
setup_k8s_k9s_shell_pod_namespace: default

setup_yc_disk_dir: "{{ setup_system_user_home }}/my-disk"
setup_yc_disk_config_dir: "{{ setup_system_user_home }}/.config/yandex-disk"
setup_yc_disk_exclude_dirs: ""
